import java.io.*;
import java.util.*;

public class ExceptClass1 {
	public static void main(String[] args) {
		try {
			Scanner sc = new Scanner(System.in);
			int[] a = new int[3];
			System.out.println("Enter the numerator for division: ");
			a[0] = sc.nextInt();
			System.out.println("Enter the denomenator for division: ");
			a[1] = sc.nextInt();
			try {
				a[2] = a[0] / a[1];
				if (a[2] == 10)
					throw new IOException("File Problem!");
				System.out.println("Result : " + a[2]);
			} catch (ArithmeticException e) {
				System.out.println(e);

			} catch (IndexOutOfBoundsException e) {
				System.out.println(e);

			} catch (Exception e) {
				System.out.println("Partially Handlied IO Exception: " + e);
				throw e;

			} finally {
				System.out.println("Finally block always executes..");
			}

		} catch (Exception e) {
			if(e instanceof IOException){
				System.out.println("Fully handling the Exception: " + e);
			}
			System.out.println("This is outer catch block handling: " + e);
		}

		System.out.println("Continue in my code...");
	}

}
